// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6T_h8Dze2GR2z7klnF43XVgoRrdqUNfQ',
    appId: '1:220508481751:web:094aeae73267dacf32a892',
    messagingSenderId: '220508481751',
    projectId: 'lategram-99fd2',
    authDomain: 'lategram-99fd2.firebaseapp.com',
    storageBucket: 'lategram-99fd2.appspot.com',
    measurementId: 'G-7W9BQ9SNZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDg9F9I94ucIzoJSasumS09rGO4jMBTN5s',
    appId: '1:220508481751:android:6cbb78ced15ccc9332a892',
    messagingSenderId: '220508481751',
    projectId: 'lategram-99fd2',
    storageBucket: 'lategram-99fd2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvrc_96EuNBOuo77iV9upoVfn0GCWaxRA',
    appId: '1:220508481751:ios:d9bbc6e3a3e3f3bd32a892',
    messagingSenderId: '220508481751',
    projectId: 'lategram-99fd2',
    storageBucket: 'lategram-99fd2.appspot.com',
    iosBundleId: 'com.example.lategram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvrc_96EuNBOuo77iV9upoVfn0GCWaxRA',
    appId: '1:220508481751:ios:cce44f6629e026c732a892',
    messagingSenderId: '220508481751',
    projectId: 'lategram-99fd2',
    storageBucket: 'lategram-99fd2.appspot.com',
    iosBundleId: 'com.example.lategram.RunnerTests',
  );
}
